site_name: Encycolepedia
theme:
  name: readthedocs
  locale: en
  highlightjs: true
  palette:
    scheme: slate
  font: 
    text: default
    code: Roboto Mono
  features:
    - contents.tooltips
    - content.code.copy
    - content.code.select
  plugins:
    #    - search
    - open-in-new-tab
  markdown_extensions:
    - abbr
    - attr_list
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
  nav:
    - Home: test.md
